In [2]:
import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
df.shape

(569, 31)

In [7]:
df.iloc[:,1:]

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [8]:
df.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [9]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [10]:
x_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
1,20.570,17.77,132.90,1326.0,0.08474,0.07864,0.086900,0.070170,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.241600,0.18600,0.2750,0.08902
42,19.070,24.81,128.30,1104.0,0.09081,0.21900,0.210700,0.099610,0.2310,0.06343,...,24.09,33.17,177.40,1651.0,0.12470,0.74440,0.724200,0.24930,0.4670,0.10380
337,18.770,21.43,122.90,1092.0,0.09116,0.14020,0.106000,0.060900,0.1953,0.06083,...,24.54,34.37,161.10,1873.0,0.14980,0.48270,0.463400,0.20480,0.3679,0.09870
423,13.660,19.13,89.46,575.3,0.09057,0.11470,0.096570,0.048120,0.1848,0.06181,...,15.14,25.50,101.40,708.8,0.11470,0.31670,0.366000,0.14070,0.2744,0.08839
140,9.738,11.97,61.24,288.5,0.09250,0.04102,0.000000,0.000000,0.1903,0.06422,...,10.62,14.10,66.53,342.9,0.12340,0.07204,0.000000,0.00000,0.3105,0.08151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,13.050,18.59,85.09,512.0,0.10820,0.13040,0.096030,0.056030,0.2035,0.06501,...,14.19,24.85,94.22,591.2,0.13430,0.26580,0.257300,0.12580,0.3113,0.08317
54,15.100,22.02,97.26,712.8,0.09056,0.07081,0.052530,0.033340,0.1616,0.05684,...,18.10,31.69,117.70,1030.0,0.13890,0.20570,0.271200,0.15300,0.2675,0.07873
360,12.540,18.07,79.42,491.9,0.07436,0.02650,0.001194,0.005449,0.1528,0.05185,...,13.72,20.98,86.82,585.7,0.09293,0.04327,0.003581,0.01635,0.2233,0.05521
324,12.200,15.21,78.01,457.9,0.08673,0.06545,0.019940,0.016920,0.1638,0.06129,...,13.75,21.38,91.11,583.1,0.12560,0.19280,0.116700,0.05556,0.2661,0.07961
110,9.777,16.99,62.50,290.2,0.10370,0.08404,0.043340,0.017780,0.1584,0.07065,...,11.05,21.47,71.68,367.0,0.14670,0.17650,0.130000,0.05334,0.2533,0.08468

In [11]:
x_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
93,13.45,18.30,86.60,555.1,0.10220,0.08165,0.03974,0.02780,0.1638,0.05710,...,15.10,25.94,97.59,699.4,0.1339,0.1751,0.13810,0.07911,0.2678,0.06603
75,16.07,19.65,104.10,817.7,0.09168,0.08424,0.09769,0.06638,0.1798,0.05391,...,19.77,24.56,128.80,1223.0,0.1500,0.2045,0.28290,0.15200,0.2650,0.06387
255,13.96,17.05,91.43,602.4,0.10960,0.12790,0.09789,0.05246,0.1908,0.06130,...,16.39,22.07,108.10,826.0,0.1512,0.3262,0.32090,0.13740,0.3068,0.07957
460,17.08,27.15,111.20,930.9,0.09898,0.11100,0.10070,0.06431,0.1793,0.06281,...,22.96,34.49,152.10,1648.0,0.1600,0.2444,0.26390,0.15550,0.3010,0.09060
369,22.01,21.90,147.20,1482.0,0.10630,0.19540,0.24480,0.15010,0.1824,0.06140,...,27.66,25.80,195.00,2227.0,0.1294,0.3885,0.47560,0.24320,0.2741,0.08574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,16.50,18.29,106.60,838.1,0.09686,0.08468,0.05862,0.04835,0.1495,0.05593,...,18.13,25.45,117.20,1009.0,0.1338,0.1679,0.16630,0.09123,0.2394,0.06469
188,11.81,17.39,75.27,428.9,0.10070,0.05562,0.02353,0.01553,0.1718,0.05780,...,12.57,26.48,79.57,489.5,0.1356,0.1000,0.08803,0.04306,0.3200,0.06576
201,17.54,19.32,115.10,951.6,0.08968,0.11980,0.10360,0.07488,0.1506,0.05491,...,20.42,25.84,139.50,1239.0,0.1381,0.3420,0.35080,0.19390,0.2928,0.07867
209,15.27,12.91,98.17,725.5,0.08182,0.06230,0.05892,0.03157,0.1359,0.05526,...,17.38,15.92,113.70,932.7,0.1222,0.2186,0.29620,0.10350,0.2320,0.07474
542,14.74,25.42,94.70,668.6,0.08275,0.07214,0.04105,0.03027,0.1840,0.05680,...,16.51,32.29,107.40,826.4,0.1060,0.1376,0.16110,0.10950,0.2722,0.06956

Scaling

In [12]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [13]:
x_train_scaled

array([[ 1.88040734, -0.36802083,  1.73620059, ...,  1.16639623,
        -0.20442125,  0.28273715],
       [ 1.45374929,  1.270082  ,  1.54642504, ...,  2.14531116,
         2.88454492,  1.09072751],
       [ 1.36841768,  0.48360649,  1.32364504, ...,  1.45713242,
         1.2901879 ,  0.81192164],
       ...,
       [-0.40363539, -0.29821531, -0.47014649, ..., -1.45718857,
        -1.03618974, -1.5655818 ],
       [-0.50034454, -0.96369458, -0.52831682, ..., -0.85081804,
        -0.3476077 , -0.23168702],
       [-1.1895395 , -0.54951518, -1.16819048, ..., -0.88514965,
        -0.55353878,  0.04547882]], shape=(455, 30))

In [14]:
x_test_scaled

array([[-1.44796175e-01, -2.44697747e-01, -1.73931606e-01, ...,
        -4.86624571e-01, -3.20257478e-01, -9.74075998e-01],
       [ 6.00433207e-01,  6.94270853e-02,  5.48040606e-01, ...,
         6.40596743e-01, -3.65304901e-01, -1.09215849e+00],
       [ 2.67559916e-04, -5.35554072e-01,  2.53327242e-02, ...,
         4.14812257e-01,  3.07188775e-01, -2.33873734e-01],
       ...,
       [ 1.01855809e+00, -7.35898466e-03,  1.00185171e+00, ...,
         1.28856729e+00,  8.19516585e-02, -2.83074771e-01],
       [ 3.72882251e-01, -1.49887022e+00,  3.03395165e-01, ...,
        -1.09440762e-01, -8.96220961e-01, -4.97919298e-01],
       [ 2.22129742e-01,  1.41201989e+00,  1.60238389e-01, ...,
        -1.66526170e-02, -2.49468670e-01, -7.81098599e-01]],
      shape=(114, 30))

In [15]:
y_train

1      M
42     M
337    M
423    B
140    B
      ..
356    B
54     M
360    B
324    B
110    B
Name: diagnosis, Length: 455, dtype: object

In [16]:
y_test

93     B
75     M
255    M
460    M
369    M
      ..
363    B
188    B
201    M
209    B
542    B
Name: diagnosis, Length: 114, dtype: object

Encoding

In [17]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [18]:
y_train_encoded

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0])

In [19]:
y_test_encoded

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0])

In [20]:
x_train_scaled
x_test_scaled
y_train_encoded
y_test_encoded
print("")

In [21]:
x_train_tensor = torch.from_numpy(x_train_scaled)
x_test_tensor = torch.from_numpy(x_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded).to(torch.float64)
y_test_tensor = torch.from_numpy(y_test_encoded).to(torch.float64)

In [22]:
x_train_tensor.shape[1]

30

In [23]:
y_train.shape

(455,)

This means that there will be 30 input going to the network and 1 output comming out of there (M or B)

In [24]:
# at the rate which the model steps move
learning_rate = 0.1
# number of times we send the whole dataset to the ANN
epochs = 22

In [35]:
# defining the model
class ANN():
    def __init__(self, X):
        self.weight = torch.rand((X.shape[1], 1), dtype= torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)
    
    def forward_pass(self, X):
        z = X @ self.weight + self.bias
        self.y_pred = torch.sigmoid(z).reshape(X.shape[0])
        return self.y_pred
    
    def loss_function(self, y_real):
        loss_fn = torch.nn.BCELoss()
        print(self.y_pred)
        print(y_real)
        self.loss = loss_fn(self.y_pred, y_real)
        return self.loss.item()
    
    def backward_propagation(self, learning_rate):
        self.loss.backward()
        gradient = self.weight.grad
        with torch.no_grad():
            self.weight -=learning_rate * gradient
        self.weight.grad.zero_()
        return self.weight

In [39]:
model = ANN(x_train_tensor)

1. Forward Propagation
2. Loss Calculation
3. Backward Propagtation
4. Adjustment

In [ ]:
import time
# for epoch in range(epochs):
y_prep = model.forward_pass(x_train_tensor)
loss = model.loss_function(y_train_tensor)
print("epoch: ", 1, "====> loss", loss)
new_weight = model.backward_propagation(learning_rate)

tensor([9.6720e-01, 1.0000e+00, 1.0000e+00, 5.7887e-02, 9.9062e-07, 1.0000e+00,
        1.0566e-01, 1.0884e-03, 7.8053e-04, 9.9992e-01, 3.4402e-07, 6.7478e-05,
        1.6551e-05, 4.2689e-06, 8.6862e-04, 1.5828e-04, 8.7958e-01, 1.3268e-06,
        9.9947e-01, 1.3084e-01, 5.0332e-03, 1.0000e+00, 1.7064e-02, 9.9997e-01,
        3.4191e-03, 1.6966e-04, 9.9999e-01, 9.9289e-01, 9.6589e-05, 1.3253e-03,
        1.5674e-02, 3.1158e-06, 1.4491e-06, 4.7336e-01, 5.9378e-01, 2.9655e-03,
        1.5403e-02, 2.9523e-01, 5.4065e-02, 9.8167e-01, 4.6444e-01, 9.9707e-01,
        3.4747e-04, 1.0330e-03, 1.9666e-02, 1.0000e+00, 6.9848e-01, 9.7897e-01,
        8.5300e-02, 1.0000e+00, 8.7232e-01, 4.7538e-01, 1.0000e+00, 4.4419e-03,
        9.9999e-01, 1.7665e-04, 1.0000e+00, 4.1791e-05, 6.0880e-02, 4.2259e-01,
        9.9989e-01, 1.5352e-02, 1.5783e-02, 1.7698e-04, 5.2774e-04, 6.4317e-04,
        9.9379e-01, 2.7531e-02, 3.0671e-03, 1.0000e+00, 9.9986e-01, 8.8967e-05,
        1.0203e-01, 9.2426e-05, 1.0480e-04, 1.8241e-05, 1.0824e-04, 9.9728e-01,
        1.1533e-02, 6.1505e-06, 4.6629e-01, 9.9986e-01, 1.0000e+00, 1.8171e-06,
        1.3348e-03, 1.3892e-02, 9.9999e-01, 3.9411e-02, 1.4705e-01, 7.3595e-04,
        9.0861e-03, 1.7597e-05, 1.0000e+00, 9.9398e-01, 9.9999e-01, 1.7118e-03,
        9.9991e-01, 1.3691e-02, 3.4311e-05, 3.6385e-05, 1.5389e-02, 9.9587e-01,
        3.5975e-02, 1.0000e+00, 7.2282e-01, 8.0926e-01, 3.6225e-03, 3.2713e-07,
        9.6615e-02, 1.5828e-04, 8.4834e-03, 1.0000e+00, 1.0000e+00, 4.1694e-03,
        4.7806e-07, 9.9459e-01, 1.0000e+00, 1.3178e-02, 9.3634e-02, 1.0000e+00,
        4.6186e-05, 7.4491e-01, 3.8105e-05, 1.1330e-01, 4.6697e-01, 9.9999e-01,
        3.4133e-03, 7.1558e-06, 9.9990e-01, 6.4940e-02, 8.7505e-01, 1.8907e-02,
        9.9957e-01, 3.5280e-04, 9.9994e-01, 9.3476e-05, 5.6875e-04, 3.2903e-04,
        4.7401e-01, 1.0000e+00, 6.3417e-03, 5.7922e-02, 7.6384e-02, 2.4845e-07,
        6.6252e-03, 3.2763e-07, 1.0000e+00, 9.1057e-03, 7.0986e-05, 4.0913e-04,
        7.4150e-07, 2.3889e-04, 1.0000e+00, 3.4127e-05, 3.2271e-04, 9.9056e-01,
        8.2435e-04, 9.9966e-01, 9.9999e-01, 6.0527e-05, 8.6214e-04, 3.4271e-03,
        2.1570e-03, 9.1741e-01, 9.9922e-01, 5.6792e-05, 6.1670e-04, 6.1064e-03,
        3.6659e-04, 2.9170e-05, 1.0000e+00, 1.4757e-03, 9.7673e-01, 9.4041e-01,
        1.0000e+00, 2.8752e-01, 1.6797e-05, 1.5106e-03, 3.9331e-03, 9.5177e-01,
        6.3515e-04, 4.9535e-01, 3.8480e-02, 9.9355e-02, 9.0989e-03, 3.3856e-04,
        2.1896e-03, 5.4700e-02, 5.7927e-04, 7.4035e-03, 9.6066e-01, 9.5024e-01,
        2.3009e-02, 2.8096e-04, 9.9996e-01, 2.7820e-01, 9.9349e-01, 8.9809e-05,
        8.6503e-03, 1.0000e+00, 4.1549e-05, 1.3749e-01, 9.9932e-01, 9.2060e-02,
        2.3380e-03, 1.0000e+00, 7.5503e-03, 1.0000e+00, 3.3805e-02, 9.9999e-01,
        9.9462e-01, 1.0919e-02, 7.8233e-02, 9.9987e-01, 1.9869e-05, 4.3675e-02,
        1.5282e-03, 3.6845e-05, 7.7257e-03, 1.0000e+00, 9.8156e-01, 9.9885e-01,
        7.6157e-04, 1.0000e+00, 5.9179e-01, 6.0825e-06, 4.7676e-01, 9.9983e-01,
        1.2487e-01, 9.9999e-01, 9.9997e-01, 2.1514e-01, 6.9129e-05, 9.9238e-01,
        6.1138e-06, 1.1685e-06, 3.8815e-02, 3.4195e-03, 9.9999e-01, 2.8743e-03,
        2.7753e-03, 3.2217e-02, 1.0169e-06, 6.8609e-04, 1.0000e+00, 9.9997e-01,
        8.0615e-01, 3.2413e-05, 8.8773e-06, 4.2659e-03, 5.3744e-01, 5.3620e-01,
        9.7870e-01, 9.9326e-01, 2.0811e-03, 1.4907e-05, 1.0000e+00, 4.5828e-04,
        3.5633e-05, 2.2615e-04, 3.0555e-02, 3.6557e-01, 9.9986e-01, 9.4157e-03,
        3.6068e-01, 2.3132e-03, 1.1908e-04, 9.8501e-01, 1.0941e-04, 2.1466e-04,
        9.8381e-01, 3.8179e-03, 1.0000e+00, 3.3068e-05, 9.9960e-01, 1.0000e+00,
        1.0000e+00, 9.9966e-01, 9.9956e-01, 6.7272e-01, 1.0000e+00, 1.5827e-06,
        9.9750e-01, 9.7161e-01, 8.8774e-02, 2.1079e-03, 1.0000e+00, 3.9462e-04,
        2.8316e-02, 9.9756e-01, 9.9778e-01, 4.2365e-05, 9.5865e-01, 1.0000e+00,
        1.3100e-04, 4.8867e-04, 1.0000e+00, 2.9092e-02, 9.9627e-01, 1.0000e+00,
        9.1254e-02, 9.9992e-01, 2.7923e-04, 2.8720e-03, 6.4194e-03, 1.5788e-04,
        9.9997e-01, 1.0000e+00, 2.3632e-01, 9.6736e-04, 1.0000e+00, 9.9949e-01,
        3.0579e-04, 1.0000e+00, 1.8239e-02, 5.0331e-04, 1.0000e+00, 4.9875e-02,
        6.8414e-01, 9.7313e-01, 1.0370e-05, 1.6341e-03, 7.7259e-04, 1.0199e-02,
        1.0000e+00, 9.5810e-06, 9.1508e-07, 9.9685e-01, 2.0077e-03, 1.0000e+00,
        2.1326e-04, 1.7483e-01, 9.1155e-01, 3.7929e-01, 4.5627e-03, 9.9934e-01,
        4.9131e-06, 7.6881e-02, 6.2823e-01, 9.9740e-01, 5.6400e-04, 4.5853e-01,
        2.8683e-01, 9.9996e-01, 1.5474e-02, 9.9968e-01, 4.2378e-01, 1.2530e-02,
        3.7964e-04, 1.0000e+00, 3.2490e-01, 3.9492e-05, 2.4297e-02, 9.9580e-01,
        1.0000e+00, 1.0000e+00, 1.8090e-02, 5.9183e-03, 1.0000e+00, 3.8549e-04,
        2.4063e-05, 6.8342e-01, 9.9959e-01, 1.0000e+00, 1.0000e+00, 6.9262e-06,
        2.5076e-03, 2.2774e-03, 9.9997e-01, 2.4541e-03, 1.1871e-05, 9.7308e-01,
        9.9991e-01, 9.9874e-01, 1.1286e-02, 9.6225e-03, 2.9036e-05, 9.4449e-01,
        5.0493e-03, 3.8897e-03, 1.8327e-03, 1.1418e-04, 4.3124e-07, 9.9949e-01,
        5.3936e-06, 4.4964e-03, 1.0863e-05, 1.0000e+00, 4.5356e-02, 1.9196e-04,
        9.9972e-01, 2.2906e-02, 9.9701e-01, 9.9986e-01, 1.0000e+00, 1.4327e-01,
        3.3468e-01, 2.0441e-01, 9.9987e-01, 9.7435e-01, 2.0677e-02, 4.6914e-05,
        3.7367e-05, 9.9999e-01, 3.6266e-04, 1.0000e+00, 1.0000e+00, 8.2098e-01,
        7.0689e-02, 3.5263e-01, 1.0000e+00, 1.0000e+00, 3.4187e-05, 1.0000e+00,
        3.4920e-01, 7.4492e-05, 3.2795e-03, 1.4672e-03, 2.7474e-01, 2.1596e-02,
        6.9116e-03, 9.9976e-01, 2.3031e-02, 9.9752e-01, 3.3734e-03, 2.5189e-03,
        2.7571e-04, 9.9247e-02, 1.9744e-02, 9.7204e-01, 2.1095e-05, 9.3538e-01,
        1.0000e+00, 8.5233e-01, 1.0000e+00, 6.2938e-05, 4.5710e-04, 9.9999e-01,
        2.2206e-03, 9.9980e-01, 2.4589e-04, 9.9997e-01, 3.3042e-04, 3.6328e-03,
        7.3080e-01, 9.2783e-01, 9.0786e-01, 1.8267e-05, 1.2487e-01, 8.5768e-01,
        9.4520e-01, 2.9710e-02, 1.6713e-06, 8.2545e-05, 8.3051e-02],
       dtype=torch.float64, grad_fn=<ViewBackward0>)
tensor([1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
        0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
        0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
        0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
        1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
        1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
        0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
        0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
        1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 1., 0., 0., 0.], dtype=torch.float64)
epoch:  1 ====> loss 0.5679296680363108

In [33]:
# testing the ANN
y_pred = model.forward_pass(x_test_tensor)
loss = model.loss_function(y_test_tensor)
print(loss)

ded
torch.Size([114])
torch.Size([114])
0.44235832720981566

In [34]:
y_pred

tensor([1.3297e-02, 6.4836e-01, 6.7868e-01, 9.9990e-01, 9.9999e-01, 1.0000e+00,
        1.0000e+00, 9.9954e-01, 9.9963e-01, 9.9995e-01, 1.0303e-03, 7.5070e-01,
        2.8130e-03, 7.8867e-01, 1.0000e+00, 9.9637e-01, 9.9984e-01, 9.9782e-01,
        9.4853e-03, 5.6594e-04, 9.9995e-01, 1.5501e-01, 9.9995e-01, 5.8213e-03,
        8.4029e-04, 9.9902e-01, 7.1105e-03, 4.3845e-04, 9.9999e-01, 8.0312e-03,
        9.7929e-01, 9.1243e-01, 1.6546e-01, 8.5549e-03, 9.9994e-01, 3.0309e-03,
        3.0289e-03, 9.9998e-01, 1.3845e-01, 2.7526e-04, 9.9997e-01, 9.9922e-01,
        3.8286e-02, 8.2722e-03, 9.9963e-01, 3.1366e-02, 5.4216e-01, 2.9621e-04,
        9.9846e-01, 6.9879e-02, 1.7943e-03, 8.9302e-01, 3.0609e-03, 8.6148e-05,
        2.1955e-05, 1.0000e+00, 1.6246e-01, 1.0000e+00, 3.3711e-03, 8.7672e-01,
        1.2659e-04, 1.0000e+00, 9.9678e-01, 5.5418e-01, 2.8424e-01, 8.6851e-01,
        8.9081e-01, 1.6312e-01, 9.9826e-01, 1.9292e-01, 9.9980e-01, 8.3709e-01,
        1.0000e+00, 5.4406e-01, 5.8476e-02, 9.3763e-01, 1.0000e+00, 1.5253e-05,
        3.7284e-03, 9.9997e-01, 9.9994e-01, 2.8745e-04, 9.9887e-01, 3.2769e-01,
        5.4156e-02, 8.9835e-04, 3.6199e-05, 8.7206e-01, 2.3012e-01, 5.6892e-01,
        6.2858e-03, 4.7049e-05, 1.0000e+00, 1.1789e-02, 1.0000e+00, 1.3089e-04,
        9.9858e-01, 1.4690e-01, 9.9914e-01, 3.0169e-02, 9.9974e-01, 2.1724e-04,
        7.9486e-05, 9.9465e-01, 9.9839e-01, 1.0000e+00, 8.4033e-01, 1.0000e+00,
        2.6574e-04, 5.0652e-02, 2.5027e-03, 7.9658e-01, 2.0109e-04, 5.7963e-02],
       dtype=torch.float64, grad_fn=<ViewBackward0>)

In [42]:
y_test_tensor

tensor([0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
        1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1.,
        0., 1., 0., 0., 0., 1.], dtype=torch.float64)

In [43]:
y_train_tensor

tensor([1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
        0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
        1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
        1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
        1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
        0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
        1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
        1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1.,
        0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0.,
        0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
        1., 0., 0., 0., 0.], dtype=torch.float64)