In [1]:
import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [4]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [5]:
df.shape

(569, 31)

In [6]:
df.iloc[:,1:]

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [7]:
df.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [8]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [9]:
x_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
392,15.49,19.97,102.40,744.7,0.11600,0.15620,0.189100,0.091130,0.1929,0.06744,...,21.20,29.41,142.10,1359.0,0.1681,0.39130,0.55530,0.21210,0.3187,0.10190
20,13.08,15.71,85.63,520.0,0.10750,0.12700,0.045680,0.031100,0.1967,0.06811,...,14.50,20.49,96.09,630.5,0.1312,0.27760,0.18900,0.07283,0.3184,0.08183
544,13.87,20.70,89.77,584.8,0.09578,0.10180,0.036880,0.023690,0.1620,0.06688,...,15.05,24.75,99.17,688.6,0.1264,0.20370,0.13770,0.06845,0.2249,0.08492
196,13.77,22.29,90.63,588.9,0.12000,0.12670,0.138500,0.065260,0.1834,0.06877,...,16.39,34.01,111.60,806.9,0.1737,0.31220,0.38090,0.16730,0.3080,0.09333
121,18.66,17.12,121.40,1077.0,0.10540,0.11000,0.145700,0.086650,0.1966,0.06213,...,22.25,24.90,145.40,1549.0,0.1503,0.22910,0.32720,0.16740,0.2894,0.08456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,13.78,15.79,88.37,585.9,0.08817,0.06718,0.010550,0.009937,0.1405,0.05848,...,15.27,17.50,97.90,706.6,0.1072,0.10710,0.03517,0.03312,0.1859,0.06810
299,10.51,23.09,66.85,334.2,0.10150,0.06797,0.024950,0.018750,0.1695,0.06556,...,10.93,24.22,70.10,362.7,0.1143,0.08614,0.04158,0.03125,0.2227,0.06777
218,19.80,21.56,129.70,1230.0,0.09383,0.13060,0.127200,0.086910,0.2094,0.05581,...,25.73,28.64,170.30,2009.0,0.1353,0.32350,0.36170,0.18200,0.3070,0.08255
306,13.20,15.82,84.07,537.3,0.08511,0.05251,0.001461,0.003261,0.1632,0.05894,...,14.41,20.45,92.00,636.9,0.1128,0.13460,0.01120,0.02500,0.2651,0.08385
399,11.80,17.26,75.26,431.9,0.09087,0.06232,0.028530,0.016380,0.1847,0.06019,...,13.45,24.49,86.00,562.0,0.1244,0.17260,0.14490,0.05356,0.2779,0.08121

In [10]:
x_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
207,17.01,20.26,109.70,904.3,0.08772,0.07304,0.06950,0.05390,0.2026,0.05223,...,19.80,25.05,130.00,1210.0,0.11110,0.1486,0.19320,0.10960,0.3275,0.06469
437,14.04,15.98,89.78,611.2,0.08458,0.05895,0.03534,0.02944,0.1714,0.05898,...,15.66,21.58,101.20,750.0,0.11950,0.1252,0.11170,0.07453,0.2725,0.07234
79,12.86,18.00,83.19,506.3,0.09934,0.09546,0.03889,0.02315,0.1718,0.05997,...,14.24,24.82,91.88,622.1,0.12890,0.2141,0.17310,0.07926,0.2779,0.07918
220,13.65,13.16,87.88,568.9,0.09646,0.08711,0.03888,0.02563,0.1360,0.06344,...,15.34,16.35,99.71,706.2,0.13110,0.2474,0.17590,0.08056,0.2380,0.08718
92,13.27,14.76,84.74,551.7,0.07355,0.05055,0.03261,0.02648,0.1386,0.05318,...,16.36,22.35,104.50,830.6,0.10060,0.1238,0.13500,0.10010,0.2027,0.06206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,12.90,15.92,83.74,512.2,0.08677,0.09509,0.04894,0.03088,0.1778,0.06235,...,14.48,21.82,97.17,643.8,0.13120,0.2548,0.20900,0.10120,0.3549,0.08118
157,16.84,19.46,108.40,880.2,0.07445,0.07223,0.05150,0.02771,0.1844,0.05268,...,18.22,28.07,120.30,1032.0,0.08774,0.1710,0.18820,0.08436,0.2527,0.05972
354,11.14,14.07,71.24,384.6,0.07274,0.06064,0.04505,0.01471,0.1690,0.06083,...,12.12,15.82,79.62,453.5,0.08864,0.1256,0.12010,0.03922,0.2576,0.07018
139,11.28,13.39,73.00,384.8,0.11640,0.11360,0.04635,0.04796,0.1771,0.06072,...,11.92,15.77,76.53,434.0,0.13670,0.1822,0.08669,0.08611,0.2102,0.06784
293,11.85,17.46,75.54,432.7,0.08372,0.05642,0.02688,0.02280,0.1875,0.05715,...,13.06,25.75,84.35,517.8,0.13690,0.1758,0.13160,0.09140,0.3101,0.07007

Scaling

In [11]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [12]:
x_train_scaled

array([[ 0.39930427,  0.16182987,  0.44245379, ...,  1.52584937,
         0.50798114,  1.05433991],
       [-0.29432964, -0.82686971, -0.25642717, ..., -0.63723821,
         0.5028367 , -0.10491757],
       [-0.06695587,  0.33125491, -0.08389484, ..., -0.70526667,
        -1.10051588,  0.07356303],
       ...,
       [ 1.6397865 ,  0.53085154,  1.58016697, ...,  1.05834786,
         0.30734772, -0.06332986],
       [-0.25979185, -0.80133991, -0.32143935, ..., -1.3801152 ,
        -0.41116002,  0.01175907],
       [-0.66273271, -0.4671316 , -0.68859148, ..., -0.93653237,
        -0.19166362, -0.14072921]], shape=(455, 30))

In [13]:
x_test_scaled

array([[ 0.83678292,  0.2291357 ,  0.74667746, ..., -0.06614084,
         0.65888491, -1.09493617],
       [-0.01802733, -0.76420565, -0.0834781 , ..., -0.61083447,
        -0.28426366, -0.65306673],
       [-0.35764892, -0.29538567, -0.35811289, ..., -0.53736994,
        -0.19166362, -0.25798346],
       ...,
       [-0.85269055, -1.20749584, -0.85612288, ..., -1.15925568,
        -0.53977119, -0.77782986],
       [-0.81239646, -1.36531643, -0.7827758 , ..., -0.4309784 ,
        -1.35259378, -0.91298993],
       [-0.64834197, -0.42071378, -0.67692263, ..., -0.34881617,
         0.360507  , -0.78418354]], shape=(114, 30))

In [14]:
y_train

392    M
20     B
544    B
196    M
121    M
      ..
442    B
299    B
218    M
306    B
399    B
Name: diagnosis, Length: 455, dtype: object

In [15]:
y_test

207    M
437    B
79     B
220    B
92     B
      ..
143    B
157    B
354    B
139    B
293    B
Name: diagnosis, Length: 114, dtype: object

Encoding

In [16]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [17]:
y_train_encoded

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [18]:
y_test_encoded

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0])

In [19]:
x_train_scaled
x_test_scaled
y_train_encoded
y_test_encoded
print("")

In [20]:
x_train_tensor = torch.from_numpy(x_train_scaled)
x_test_tensor = torch.from_numpy(x_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded).to(torch.float64)
y_test_tensor = torch.from_numpy(y_test_encoded).to(torch.float64)

In [21]:
x_train_tensor.shape[1]

30

In [22]:
y_train.shape

(455,)

This means that there will be 30 input going to the network and 1 output comming out of there (M or B)

In [23]:
# at the rate which the model steps move
learning_rate = 0.1
# number of times we send the whole dataset to the ANN
epochs = 22

In [24]:
# defining the model

class ANN():
    def __init__(self, X):
        self.weight = torch.rand((X.shape[1], 1), dtype= torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)
    
    def forward_pass(self, X):
        z = X @ self.weight + self.bias
        self.y_pred = torch.sigmoid(z).reshape(X.shape[0])
        return self.y_pred
    
    def loss_function(self, y_real):
        loss_fn = torch.nn.BCELoss()
        self.loss = loss_fn(self.y_pred, y_real)
        return self.loss.item()
    
    def backward_propagation(self, learning_rate):
        self.loss.backward()
        gradient = self.weight.grad
        with torch.no_grad():
            self.weight -=learning_rate * gradient
        self.weight.grad.zero_()
        return self.weight

In [25]:
model = ANN(x_train_tensor)

1. Forward Propagation
2. Loss Calculation
3. Backward Propagtation
4. Adjustment

In [26]:
import time
for epoch in range(epochs):
    y_prep = model.forward_pass(x_train_tensor)
    loss = model.loss_function(y_train_tensor)
    print("epoch: ", epoch, "====> loss", loss)
    new_weight = model.backward_propagation(learning_rate)

epoch:  0 ====> loss 0.6369613453228048
epoch:  1 ====> loss 0.6146598705404469
epoch:  2 ====> loss 0.5930438700902142
epoch:  3 ====> loss 0.5721003429918428
epoch:  4 ====> loss 0.5518164128323542
epoch:  5 ====> loss 0.5321791255775542
epoch:  6 ====> loss 0.5131751341268191
epoch:  7 ====> loss 0.4947906677062791
epoch:  8 ====> loss 0.4770115548794694
epoch:  9 ====> loss 0.4598234334086027
epoch:  10 ====> loss 0.4432120534744004
epoch:  11 ====> loss 0.42716365864567113
epoch:  12 ====> loss 0.4116654021818303
epoch:  13 ====> loss 0.3967057544113486
epoch:  14 ====> loss 0.382274848458865
epoch:  15 ====> loss 0.36836469308445474
epoch:  16 ====> loss 0.354969163526567
epoch:  17 ====> loss 0.34208368033781644
epoch:  18 ====> loss 0.32970452141954687
epoch:  19 ====> loss 0.31782780212593337
epoch:  20 ====> loss 0.30644829137691904
epoch:  21 ====> loss 0.29555835603730596

In [27]:
# testing the ANN
y_pred = model.forward_pass(x_test_tensor)
loss = model.loss_function(y_test_tensor)
print(loss)

0.20713348457986963

In [28]:
y_pred

tensor([8.5277e-01, 1.7811e-02, 1.7237e-02, 1.3387e-03, 1.1606e-03, 2.7439e-03,
        4.0580e-02, 2.9601e-03, 1.0000e+00, 1.1761e-01, 9.9987e-01, 9.9717e-01,
        9.9499e-01, 7.1129e-01, 3.7564e-01, 9.7691e-01, 8.5751e-01, 6.1975e-01,
        8.0804e-03, 7.4584e-01, 1.2252e-03, 1.0000e+00, 1.0000e+00, 9.9960e-01,
        5.6183e-04, 5.7831e-01, 7.2596e-05, 1.0000e+00, 9.9999e-01, 9.5079e-01,
        9.9992e-01, 9.7889e-01, 3.4778e-02, 2.3505e-03, 5.6048e-02, 9.3533e-01,
        1.9037e-04, 1.8321e-01, 6.6388e-03, 1.0000e+00, 9.9999e-01, 7.8120e-02,
        4.8219e-01, 5.3827e-01, 1.2778e-02, 8.0968e-03, 1.5364e-02, 2.4483e-03,
        1.8381e-01, 9.9968e-01, 8.5090e-03, 2.6268e-02, 9.9989e-01, 2.1842e-05,
        2.6409e-02, 9.9946e-01, 9.9996e-01, 9.9151e-01, 9.9969e-01, 7.9371e-01,
        9.9844e-01, 8.6805e-01, 9.6086e-01, 1.9991e-02, 4.7268e-03, 1.0574e-02,
        4.3999e-02, 1.0000e+00, 7.4891e-02, 2.2221e-03, 5.9223e-01, 1.0000e+00,
        1.3580e-01, 9.9984e-01, 1.9342e-03, 1.1504e-04, 2.5197e-05, 9.9996e-01,
        9.9990e-01, 9.9910e-01, 2.0913e-01, 9.3548e-01, 8.8888e-02, 8.8434e-02,
        9.8557e-01, 3.5299e-02, 9.6441e-01, 1.6088e-04, 9.9997e-01, 9.9885e-01,
        1.0028e-04, 1.3003e-02, 1.6935e-03, 6.6839e-04, 9.8722e-01, 2.6242e-01,
        3.3633e-04, 9.5282e-01, 3.0593e-05, 2.2865e-01, 1.7740e-04, 1.0000e+00,
        5.7256e-05, 6.5668e-02, 1.7237e-02, 9.7255e-01, 1.2005e-02, 9.9998e-01,
        1.0000e+00, 1.3824e-02, 1.8219e-01, 1.7496e-03, 2.6763e-02, 6.1116e-03],
       dtype=torch.float64, grad_fn=<ViewBackward0>)

In [29]:
y_test_tensor

tensor([1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
        0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1.,
        0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
        1., 0., 0., 0., 0., 0.], dtype=torch.float64)

In [30]:
y_train_tensor

tensor([1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
        1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
        0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
        0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.,
        0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
        1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
        0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0.,
        1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 1., 0., 0.], dtype=torch.float64)